### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'slice')

### ISSUE THREAD

**Issue by Shaun-Yao** [TimGrey998/findKing#3]
TypeError: Cannot read properties of undefined (reading 'slice')
    at getDogLogs (file:///D:/node-project/findKing-main/utils.js:172:40)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async findKing (file:///D:/node-project/findKing-main/utils.js:52:24)

nodejs 版本 v16.15.0

**Comment by TimGrey998** [comment]
可以把您的详细配置信息发给我嘛，可以打包发到我邮箱xof493493@gmail.com或者vx联系我：FOX394。感谢参与初期测试！
